/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents the session request body
 */
export interface CreateSessionRequestBody {
  /**
   * User's email
   */
  email: string;
  /**
   * User's password
   */
  password: string;
}
