/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response format after user creation submission
 */
export interface CreateUserResponseBody {
  /**
   * User's id
   */
  id: string;
  /**
   * User's email
   */
  email: string;
  /**
   * User's firstname
   */
  firstname: string;
  /**
   * User's lastname
   */
  lastname: string;
}
