/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represent data in the body after form submission for creating user
 */
export interface CreateUserRequestBody {
  /**
   * User's firstname
   */
  firstname: string;
  /**
   * User's lastname
   */
  lastname: string;
  /**
   * User's email
   */
  email: string;
  /**
   * User's password
   */
  password: string;
  /**
   * User's password confirmation
   */
  passwordConfirmation: string;
}
