name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build-mac

    - name: Audit
      run: npm audit
      
    - name: Lint with ES lint
      run: npm run lint-mac
  
#  test:
#    runs-on: ubuntu-latest
    
#    steps:
#    - name: Run tests
#      run: npm run launchTest-mac

#  lint:
#    runs-on: ubuntu-latest
    
#    steps:
#    - name: Lint with ES lint
#      run: npm run lint-mac
